NAMES={};
NAMES.Ships={
    M:'muerto',
    T:'tartaros',
    B:'belzebub',
    N:'nemezis',
    Q:'orhenes',
    U:'dregos',
    A:'carras',
    K:'koriaz',
    C:'cloaker',
    F:'fariax',
    G:'gargamon',
    S:'hajaher',
    D:'dandares',
    J:'juggernaut',
    V:'vitotas',
    E:'edison',
    H:'hiacynt',
    W:'warastein',
    I:'iskariot',
    R:'royale',
};
NAMES.ModName = {
    healerProd:  'Heal',
    esteemProd:  '<div class="smaller_title">Moves Estimation</div>',
    shieldProd:  'Shield',
    radar:       'Radar',
    ProdBullet:  'Bullets',
    ProdBomb:    'Bombs',
    ProdMissile: 'Missiles',
    laserProd:   'Laser',
    teleProd:    'Teleport',
    spotRegion:  '<div class="smaller_title">Ships Spot</div>',
};
