BBAdata['ShipNames']={
    M:'muerto',
    T:'tartaros',
    B:'belzebub',
    N:'nemezis',
    Q:'orhenes',
    U:'dregos',
    A:'carras',
    K:'koriaz',
    C:'cloaker',
    F:'fariax',
    G:'gargamon',
    S:'hajaher',
    D:'dandares',
    J:'juggernaut',
    V:'vitotas',
    E:'edison',
    H:'hiacynt',
    W:'warastein',
    I:'iskariot',
    R:'royale',
    X:'xaurus',
    Z:'zarahiash',
    iD:'durishka',
    Ht:'hirieshka',
    v:'vuvis',
    WP:'patiarch',
    PI:'pitagoras',
    Wi:'wariankiel',
    Ni:'nientes',
    SH:'shieldoorz',
    L:'loliax',
};
BBAdata['ModuleNames'] = {
    healerProd:         'Heal',
    esteemProd:         '<div class="smaller_title">Moves Estimation</div>',
    shieldProd:         'Shield',
    radar:              'Radar',
    ProdBullet:         'Bullets',
    ProdBomb:           'Bombs',
    ProdMissile:        'Missiles',
    moduleProdLaser:    'Laser',
    moduleProdMoves:    'Moves',
    moduleProdTeleJump: 'Teleport',
    spotRegion:         '<div class="smaller_title">Ships Spot</div>',
};
